export const languageData = {
  en: {
    heroTitle: "Welcome to Les Tops du Top Construction",
    heroSubtitle: "Your trusted partner in construction, roofing, and property rentals.",
    generalContractorTitle: "General Contractor", 
    generalContractorDescription: "We are a professional general contracting firm serving the Montérégie and Estrie regions, specializing in residential construction. Our expertise lies in crafting luxurious single-family homes and high-quality multi-unit dwellings, utilizing the latest technologies and premium-grade materials to deliver exceptional results.",
    servicesTitle: "Services",
    newConstruction: "New Construction",
    renovation: "Renovation",
    roofing: "Roofing",
    realisations: "Realisations",
    availableRentals: "Available Rentals",
    getRoofingQuote: "Get a Roofing Quote",
    contactUs: "Contact Us",
    partnersTitle: "Partners",
  },
  fr: {
    heroTitle: "Bienvenue chez Les Tops du Top Construction",
    heroSubtitle: "Votre partenaire de confiance en construction, toiture et location immobilière.",
    generalContractorTitle: "Entrepreneur Général",
    generalContractorDescription: "Nous sommes une entreprise de construction générale professionnelle desservant les régions de la Montérégie et de l'Estrie, spécialisée dans la construction résidentielle. Notre expertise réside dans la réalisation de maisons unifamiliales luxueuses et de logements multi-unités de haute qualité, en utilisant les dernières technologies et des matériaux de première qualité pour offrir des résultats exceptionnels.",
    servicesTitle: "Services",
    newConstruction: "Nouvelle Construction",
    renovation: "Rénovation",
    roofing: "Toiture",
    realisations: "Réalisations",
    availableRentals: "Locations Disponibles",
    getRoofingQuote: "Obtenez une Soumission",
    contactUs: "Contactez-Nous",
    partnersTitle: "Partenaires",
  },
};
